### ISSUE TITLE
Typo/Confusion - Cypher query returning varchar datatype in docs.

### ISSUE THREAD

**Issue by KamleshKumar427** [apache/age-website#113]
How a Cypher query can return varchar(50), is this some typo in the documentation or is it possible that Cypher queries can return other datatypes?

![image](https://user-images.githubusercontent.com/95052507/209471631-bb568eb6-07a5-4429-ba86-4b838c072218.png)

But on the other hand, the documentation says:
![image](https://user-images.githubusercontent.com/95052507/209471670-89a7c086-42bc-4666-98e3-b2d047eee70b.png)

link to page in documentation:
https://age.apache.org/age-manual/master/advanced/advanced.html

**Comment by Zainab-Saad** [comment]
It is not a typo. AGE supports a custom datatype 'agtype' and returns only one datatype i.e; agtype. But in addition to this, it also supports type coercion if it is possible. For example it coerces varchar(50) to agtype, bool to agtype, float to agtype etc. It only throws error if it cannot coerce the data type provided in the query.

Kindly refer to regression test [here] where this concept is explained(https://github.com/apache/age/blob/master/regress/expected/cypher.out)

**Comment by KamleshKumar427** [comment]
Okay Right, Got it thanks Zainab for clarifying it.
