### ISSUE TITLE
Do you use any netlify/CMS integration with your website? How?

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/age-website#158]
Hi, just a question. I noticed https://github.com/apache/age-website/blob/new-web/static/admin/config.yml and wondering if you're using any kind of git/headless CMS with your website? If so, how can you advise?

/cc @pdpotter @JoshInnis 

-Rohit (I'm from the Apache CloudStack community)

**Comment by pawankukreja01** [comment]
Yes, Netlify provides a variety of integrations to supercharge your workflow and extend the limits of web performance and team productivity. One of the popular integrations is Netlify CMS. It is an open-source content management system that enables you to provide editors with a friendly UI and intuitive workflows. Netlify CMS allows you to add it to your site by creating and configuring files, then connecting the CMS to your site through user authentication . It is designed to work with any static site generator and stores content in your Git repository alongside your code for easier versioning, multi-channel publishing, and the option to handle content updates directly in [Git](https://www.reveation.io/blog/integrate-netlify-cms-in-jamstack-website/)

**Comment by vinay-agens** [comment]
Netlify CMS can be integrated into your website in several ways:

1. Add the Netlify CMS dashboard: You can add the Netlify CMS dashboard at `/admin` or another route if you prefer.

2. Inject Netlify’s Identity Widget: This is done across your site to support logging in to the admin app.

3. Run a local proxy server in dev mode: This allows local content updates via the CMS.

You can also connect your Netlify site with a Contentful space using the Contentful Integration to streamline the way you work with your CMS and Netlify. Once you have your Contentful space and your Netlify site ready, you can connect to Contentful in the Netlify UI.

**Comment by rohityadavcloud** [comment]
Thanks @pawankukreja01 @vinay-agens
