### ISSUE TITLE
Outdated release notes on website

### ISSUE THREAD

**Issue by MuhammadTahaNaveed** [apache/age-website#173]
Release notes are outdated https://age.apache.org/release-notes. Currently the latest release is v1.3.0. It would be great if the website could fetch the releases from github using github's api. This would automatatically update the website whenever there is a new release and will also provide correct release notes as listed on github.

![image](https://github.com/apache/age-website/assets/85064039/1ce70a8b-403d-4633-882c-4674f96d4e6c)

**Comment by dpdjvhxm** [comment]
Updated, refer from AGE github release page. Please check it

![image](https://github.com/apache/age-website/assets/137974842/9c6874c1-5f6e-497a-8ca9-42b9fd90d2b2)

https://age.apache.org/release-notes
