### ISSUE TITLE
Location of sample CSV files for loader

### ISSUE THREAD

**Issue by LuckyLub** [apache/age-website#243]
[The documentation ](https://age.apache.org/age-manual/master/intro/agload.html#explanation-about-the-csv-format) states that example files can be found in `regress/age_load/data`. What location is being referenced here? I can't seem to find it. Although a sample is always helpful, I do think the documentation is already clear enough in its description.

**Comment by rafsun42** [comment]
It is in the apache/age repository.

**Comment by LuckyLub** [comment]
Ah, I completely missed that. Thanks! I was looking here...
