### ISSUE TITLE
Happy new years

### ISSUE THREAD

**Issue by jbiz805** [apache/age-website#245]
Copyright is still set to 2023 at the bottom of the website.

**Comment by itsdheerajdp** [comment]
Fixes #246 
I changed the year from 2023 to 2024 at the bottom of the website.

**Comment by dehowef** [comment]
@itsdheerajdp oops I merged your PR but can you make another PR to the main branch?

**Comment by itsdheerajdp** [comment]
Yeah sure , I'll make another PR to main branch

**Comment by itsdheerajdp** [comment]
Can you please clearly explain me what you want me to do as i am confused because PR is already merged so what to do now??
