### ISSUE TITLE
[Discussion] Please give us your opinion on the reform of the age website

### ISSUE THREAD

**Issue by shinhanbyeol** [apache/age-website#52]
hello ~ @apache/age-committers 

We are preparing to reorganize the age website to recruit commiter and encourage open source participation  Please check the new-web branch and give us your opinion.

**Comment by pdpotter** [comment]
Nice job! The new website looks a lot more inviting.

General remarks / questions:
* For issues, Jira is mentioned, while in practice, I think currently most new issues by new members of the community are created in Github. Should Github be mentioned instead of Jira? Should one of the 2 issue trackers be closed in favor of the other?
* For the code review process, currently a review process using e-mail and patches is described (https://github.com/apache/age-website/blob/new-web/src/pages/contribution/guide.md#code-review-process). Wouldn't it be easier to use Github Pull Requests instead of patches in e-mails?
* Will the documentation pages be generated using Gatsby as well? (currently, the documentation link links to a non-existing page). I think a link to the documentation in the footer could be practical as well.
* Some icons / elements are quite big, but of course that is a personal preference.

I've encountered some typos and missing links as well, but I think it's best to address those in a PR once the general discussion has concluded.

**Comment by JoshInnis** [comment]
Hello,

I agree with @pdpotter, on the general site and I agree with many of the point mentioned. i also noticed the age manual part of the site did not build with the instructions given

**Comment by shinhanbyeol** [comment]
> Nice job! The new website looks a lot more inviting.
> 
> General remarks / questions:
> 
> * For issues, Jira is mentioned, while in practice, I think currently most new issues by new members of the community are created in Github. Should Github be mentioned instead of Jira? Should one of the 2 issue trackers be closed in favor of the other?
> * For the code review process, currently a review process using e-mail and patches is described (https://github.com/apache/age-website/blob/new-web/src/pages/contribution/guide.md#code-review-process). Wouldn't it be easier to use Github Pull Requests instead of patches in e-mails?
> * Will the documentation pages be generated using Gatsby as well? (currently, the documentation link links to a non-existing page). I think a link to the documentation in the footer could be practical as well.
> * Some icons / elements are quite big, but of course that is a personal preference.
> 
> I've encountered some typos and missing links as well, but I think it's best to address those in a PR once the general discussion has concluded.

“Apache AGE Manual” items in the documentation menu will utilize the same resources as https://age.apache.org/docs/master/index.html

**Comment by manjung49** [comment]
> * For issues, Jira is mentioned, while in practice, I think currently most new issues by new members of the community are created in Github. Should Github be mentioned instead of Jira? Should one of the 2 issue trackers be closed in favor of the other? --- This section has been edited. We're going to encourage the users to use Github, Stackoverflow, and Reddit to share ideas, knowledge, and any issues. Thanks :) 
> Nice job! The new website looks a lot more inviting.
> 
> General remarks / questions:
> 
> * For issues, Jira is mentioned, while in practice, I think currently most new issues by new members of the community are created in Github. Should Github be mentioned instead of Jira? Should one of the 2 issue trackers be closed in favor of the other?
> * For the code review process, currently a review process using e-mail and patches is described (https://github.com/apache/age-website/blob/new-web/src/pages/contribution/guide.md#code-review-process). Wouldn't it be easier to use Github Pull Requests instead of patches in e-mails?
> * Will the documentation pages be generated using Gatsby as well? (currently, the documentation link links to a non-existing page). I think a link to the documentation in the footer could be practical as well.
> * Some icons / elements are quite big, but of course that is a personal preference.
> 
> I've encountered some typos and missing links as well, but I think it's best to address those in a PR once the general discussion has concluded.

**Comment by shinhanbyeol** [comment]
Thanks to everyone's attention and help, 
We have opened https://age.staged.apache.org
Future changes can be found here at https://age.staged.apache.org
I'd like to open a new website at age.apache.org when it's ready

**Comment by JoshInnis** [comment]
The documentation on the old site has this feature where users can view a specific released version of the documentation. The new website only contains one version, from master. I would recommend we keep that feature.

**Comment by pdpotter** [comment]
I just realized the documentation will be in another location on the new site (`age-manual` instead of `docs`). Do we want to change the location, potentially breaking links from external sites and issues?

**Comment by pdpotter** [comment]
Will the new website be build manually each time, or will a GitHub workflow be added to automate this process?

I'm going to have to make some changes to the documentation build config, as `new-web` and `documentation-staging` are incorrectly seen as documentation release branches.

**Comment by shinhanbyeol** [comment]
https://age.apache.org/
