### ISSUE TITLE
Need to fix package file

### ISSUE THREAD

**Issue by Manoj0Marmat** [apache/age-website#96]
Issue :
![Screenshot 2022-10-15 at 11 23 19 AM](https://user-images.githubusercontent.com/85970385/195971358-15e42889-e6c5-4b53-b0c9-9452b958e462.png)

Ref:
[Ref package file](https://github.com/apache/age-website/blob/new-web/package.json)

Desc:
wrong name, auther, discription

Sol:
fix apahce  -> apache

**Comment by shinhanbyeol** [comment]
Thank you.
I modified it.
https://github.com/apache/age-website/commit/ab35e53437ce99846b51acd81637796f59f29380

**Comment by Manoj0Marmat** [comment]
@shinhanbyeol hello i need quick help i'm trying to run this project on my mac but i'm getting some issues can you please help with it

**Comment by shinhanbyeol** [comment]
> @shinhanbyeol hello i need quick help i'm trying to run this project on my mac but i'm getting some issues can you please help with it

I will help you if you attach a log or screenshot of the problem you are experiencing.

**Comment by Manoj0Marmat** [comment]
can we connect on linked in https://www.linkedin.com/in/manoj-marmat/

**Comment by Manoj0Marmat** [comment]
![Screenshot 2022-10-17 at 4 46 16 PM](https://user-images.githubusercontent.com/85970385/196163671-12f9bddd-1e61-4116-95aa-aba95eb60f36.png)
i'm getting this error after run `yarn run start`
